### ISSUE TITLE
No way to connect textual channels to a roles directly

### ISSUE THREAD

**Issue by LucaMRe3** [Lucky3028/terraform-provider-discord#141]
I was working with your provider and I notice that if I wanna create a single textual channel without connecting in a category there is no way to connect to the channel a role

**Comment by Lucky3028** [comment]
@LucaMRe3 Thanks for creating a issue and I'll check this within a week.

**Comment by Lucky3028** [comment]
@LucaMRe3 
Please let me know if this is not what you want to do, but wouldn't using `discord_channel_permission` solve this issue?
https://registry.terraform.io/providers/Lucky3028/discord/latest/docs/resources/channel_permission

**Comment by LucaMRe3** [comment]
yeah, sorry I was just tired and I didn't read properly, I was
already using this resource, sorry to bother you.

Il giorno ven 17 mag 2024 alle ore 10:59 Lucky ***@***.***>
ha scritto:

**Comment by Lucky3028** [comment]
Thanks for your comments and close this issue.
