### ISSUE TITLE
Permissions configuration is insecure

### ISSUE THREAD

**Issue by spectria-limina** [Lucky3028/terraform-provider-discord#58]
I am pretty excited to configure a server through text, but a major obstacle right now is that permissions configuration is insecure:

1. Apart from channels set to sync from their category, Terraform doesn't support destroying resources that it doesn't know about. As a result, if a permission gets manually added somewhere, Terraform cannot remove it, and this will go undetected by the server admins.
2. Permission syncing from a category to a channel first removes *all* overrides from the channel before adding them back, even if they are to be unchanged. This includes overrides with denials, creating a brief window where the denial is removed and someone could have more access than they should. But this window might not be too brief if something causes the Terraform instance to fail and not put the permissions back.
    1. An error on a later permissions change will cause the Terraform instance to fail and not put the permissions back.
3. `arePermissionsSynced` appears to have spurious false negatives. I imagine this is because it assumes that permissions overrides are always sorted? Not really sure. But this makes the previous issue worse because the syncing logic can decide to sync permissions spuriously when it will actually be doing a dangerous no-op.
4. Permission syncing is not part of the generated plan, and therefore changes to permissions as a result of syncing happen without warning. This makes the previous issue still worse because now this means that a seemingly innocuous change like retitling a channel could result in a permanent (until fixed) security hole.
5. There's a lot of subtlety when modifying the permissions of categories, because of [permissions syncing](https://discord.com/developers/docs/topics/permissions#permission-syncing). It could even be triggered partway through modifying a category, causing it to "pick up" a channel into sync without Terraform ever knowing.

The quickest fix to the worst of the issues would be to perform permissions syncing atomically by overwriting the entire `permission_overwrites` field in the channel object. I also think that modeling permissions as separate resources is probably a bad idea generally and they should just be arguments on the channel resource. There isn't really a need to do permission-by-permission granular updates and it just makes configuration more verbose anyway.

The main remaining issue would be that there would need to be some way to handle channels that are not supposed to be in sync with the category, but are. I don't think there is a way to do this without breaking the hemerticity assumptions of Terraform very badly.

**Comment by Lucky3028** [comment]
What do you think I should do in the end? Considering what you have indicated, I think I have no choice but to give up on updating the permissions with Terraform.

**Comment by Lucky3028** [comment]
@spectria-limina 
Since you have not responded, I am closing this issue. If you have any questions, please feel free to comment.
