### ISSUE TITLE
Trying to change a channel category gives an error

### ISSUE THREAD

**Issue by ronaldmiranda** [Lucky3028/terraform-provider-discord#67]
when you try to change a channel category, it gives an return from cloudflare giving an 400 error

**Comment by Lucky3028** [comment]
This error was not reproduced here. Is it still occurring? @ronaldmiranda

**Comment by Lucky3028** [comment]
@ronaldmiranda 
Since you have not responded, I am closing this issue. If you have any questions, please feel free to comment.
