### ISSUE TITLE
disgord -> discordgo?

### ISSUE THREAD

**Issue by Lucky3028** [Lucky3028/terraform-provider-discord#91]
> I had never heard of discordgo before. However, since discordgo seems to be more popular than disgord, there is a way to switch to it. Thanks!

_Originally posted by @Lucky3028 in https://github.com/Lucky3028/terraform-provider-discord/issues/77#issuecomment-1453337923_

**Comment by bephinix** [comment]
This would be great to support all channel types. AFAICS, this provide only use basic features (create, update, get).
How much work would that be, what do you think @Lucky3028 ?

**Comment by Lucky3028** [comment]
I don't know because I haven't seen the code at all, but I think it's a lot of work. I don't have the motivation to do it at all, which is more of a problem than the amount of work.
@bephinix
